### PR TITLE
feat(send): add forever option to expiration timer - refs #BAC-1979

### PR DESCRIPTION
**Pull request by aesariyev**

### CODE REVIEW

**Review by alsprogrammer — CHANGES_REQUESTED** [review]
Looks good to me, but I have two notes:

* I don't know how idiomatic the code is, so @didasmbalanya could you please have a look and provide us your opinion on that (as you are way more experienced with JS than me)?
* For me the ACs in the ticket seem to be more about adding a new config parameter to the configuration of the service itself and not to the user interface (though it's great to have anyway), as for the current implementation it's still possible to set limited number of downloads or TTL for a file, while the service supposed to keep the user files forever (or until the user deletes it, or user account is deleted).

So could you please also add a configuration parameter like `KEEP_FILES_FOREVER` and when it's set to `true` set the TTL and the numebr of download for all the uploaded files to  `Never` no matter what the user selected in the web-interface?

**Comment by aesariyev** [comment]
> Looks good to me, but I have two notes:
> 
>     * I don't know how idiomatic the code is, so @didasmbalanya could you please have a look and provide us your opinion on that (as you are way more experienced with JS than me)?
> 
>     * For me the ACs in the ticket seem to be more about adding a new config parameter to the configuration of the service itself and not to the user interface (though it's great to have anyway), as for the current implementation it's still possible to set limited number of downloads or TTL for a file, while the service supposed to keep the user files forever (or until the user deletes it, or user account is deleted).
> 
> 
> So could you please also add a configuration parameter like `KEEP_FILES_FOREVER` and when it's set to `true` set the TTL and the numebr of download for all the uploaded files to `Never` no matter what the user selected in the web-interface?

Thanks for review.
I have added the logic, so when `0` comes as `expire_times_seconds` then the file will be stored "forever".
Also, we can set environment variable for `DEFAULT_EXPIRE_SECONDS` to `0`, so, this will be applied even if `expire_times_seconds` is not provided.

**Review by alsprogrammer — APPROVED** [review]
LGTM

**Comment by alsprogrammer** [comment]
However, the tests are not passed :(

**Comment by aesariyev** [comment]
> However, the tests are not passed :(

Fixed

**Pull request merged**
